### ISSUE TITLE
Reduce ISO size

### ISSUE THREAD

**Issue by danimesq** [Floflis/meta#69]

**Comment by DaniellMesquita** [comment]
- [ ] Uninstall Audacity
- [ ] Uninstall OBS
- [ ] Merge `/home` node_modules with main
- [ ] Make Electron apps depend on global modules instead of their own?
- [ ] Uninstall binaries from Siderus Orion, Arbore and Balena Etcher
- [ ] Uninstall CLI compilers, but make them installable
- [ ] Uninstall Cordova
- [ ] Use a program to manage used disk
